### ISSUE TITLE
mafia 1

### ISSUE THREAD

**Issue by YouKnow-sys** [afradley/SoulSpiral#1]
hi can you add mafia 1 dat support ?

**Comment by MeinerI** [comment]
> hi can you add mafia 1 dat support ?

Is it legal at all to write this?

**Comment by YouKnow-sys** [comment]
> > hi can you add mafia 1 dat support ?
> 
> Is it legal at all to write this?

for what? :|
i only try to mod some file

**Comment by MeinerI** [comment]
> for what? :|
> i only try to mod some file

These games are not connected in any way.

**Comment by AesirHod** [comment]
> > for what? :|
> > i only try to mod some file
> 
> These games are not connected in any way.

This. The files in mafia are in a completely different format. This only supports the Legacy of Kain games and ones that share the same engine. Mafia isn't one of them.
